Repository Kernel-GL-HRK/gl_kernel_procamp_2021, pull requests merged in 2021-12, with the labels that each got.

#4 Assignment 01_git:game/03_module/04_module
  01_git/scissors/CMakeLists.txt
  01_git/scissors/Makefile
  01_git/scissors/game_common.h
  01_git/scissors/main.c
  03_module/README.md
  03_module/solution/Makefile
  03_module/solution/buildroot_building.md
  03_module/solution/module_on_qemu.md
  03_module/solution/qemu_start_log.txt
  03_module/solution/start_qemu.sh
  03_module/solution/sum_module.c
  04_basic_struct/Makefile
  04_basic_struct/README.md
  04_basic_struct/basic_struct_module.c
  04_basic_struct/test_mod.sh
Labels: Ready for review

#80 TASK04: Implement kobject "wimbledon" with sysfs attribute "list"
  04_basic_struct/Makefile
  04_basic_struct/dump.txt
  04_basic_struct/wimbledon.c
Labels: Ready for review

#30 Task2: Implemented hwdetect script with usb and usb-uart functionality detection support
  02_bash/hwdetect/hwdetect.sh
Labels: Ready for review

#64 Vitaliy.zhyrko
  01_git/scissors/README.md
  01_git/scissors/my_random.sh
  01_git/scissors/rock-paper-scissors.sh
  scissors/README.md
  scissors/my_random.sh
  scissors/rock-paper-scissors.sh
Labels: Ready for review

#78 Task03
  03_module/README.md
  03_module/dump.txt
  03_module/src/Makefile
  03_module/src/test.sh
  03_module/src/test_module.c
Labels: Ready for review

#77 Task03: Implement basic module with params.
  03_module/Makefile
  03_module/dump.txt
  03_module/hello.c
Labels: Ready for review

#20 TASK1: rock-paper-scissors game
  01_git/Makefile
  01_git/main.c
Labels: Ready for review

#39 Task02
  02_bash/hwdetect/README.md
  02_bash/hwdetect/hwdetect.sh
Labels: Ready for review

#82 TASK02: Implement hwdetect
  02_bash/hwdetect/hwdetect.sh
Labels: Ready for review

#87 Task04: Basic structure homework VitaliyZhyrko
  04_basic_struct/src/Makefile
  04_basic_struct/src/main.c
  04_basic_struct/src/test.sh
Labels: Ready for review, Change requested

#74 TASK2: Add solution for hwdedect script
  02_bash/hwdetect/hwdetect.sh
Labels: Ready for review

#71 TASK3: Implement a basic module with params.
  03_module/Makefile
  03_module/argsmod.c
  03_module/compilation_log.txt
  03_module/console_log.txt
  03_module/dmesg_log.txt
Labels: Ready for review

#83 Task.04 and Task.05
  04_basic_struct/Makefile
  04_basic_struct/custom_attributes.c
  04_basic_struct/dmesg.log
  05_timers/README.md
  05_timers/kernelspace/Makefile
  05_timers/kernelspace/custom_timer.c
  05_timers/kernelspace/dmesg.log
  05_timers/userspace/.clang-format
  05_timers/userspace/CMakeLists.txt
  05_timers/userspace/main.cpp
  05_timers/userspace/time_manager.cpp
  05_timers/userspace/time_manager.h
  06_memory/README.md
Labels: ready, Ready for review

#38 TASK1: Add solution
  01_git/scissors/Makefile
  01_git/scissors/rpscissors.c
Labels: Ready for review

#92 Task 3: Create a simple loadable module with parameters
  03_module/log/log.txt
  03_module/src/Makefile
  03_module/src/example.c
Labels: Ready for review

#84 TASK3:Implement solution for the TASK3
  03_module/Makefile
  03_module/kernel.log
  03_module/kmodule.c
Labels: Ready for review

#96 TASK4: Implement kobject with linked list
  04_basic_struct/Makefile
  04_basic_struct/myobject.c
Labels: Ready for review

#119 Task4: Implemented basic module with linux kernel linked list data structure
  04_basic_struct/README.md
  04_basic_struct/module_bstruct/Makefile
  04_basic_struct/module_bstruct/log.txt
  04_basic_struct/module_bstruct/module_bstruct.c
Labels: Ready for review

#130 vadym.hutovskyi
  01_git/scissors/main.c
  01_git/scissors/makefile
  02_bash/hwdetect/hwdetect.sh
  03_module/TASK3/Makefile
  03_module/TASK3/TASK3.c
  03_module/TASK3/kernel_log.txt
  04_basic_struct/TASK4/Makefile
  04_basic_struct/TASK4/TASK4.c
  04_basic_struct/TASK4/log.txt
Labels: Ready for review

#133 TASK5: ready for review
  05_timers/Kernel/Makefile
  05_timers/Kernel/kernel_space.c
  05_timers/Kernel/log.txt
  05_timers/User/Makefile
  05_timers/User/log.txt
  05_timers/User/user_space.c
Labels: Ready for review

#103 Task05
  04_basic_struct/README.md
  05_timers/README.md
  05_timers/module/Makefile
  05_timers/module/my_module.c
  05_timers/module/usage_log.txt
  05_timers/program/Makefile
  05_timers/program/my_clock.c
  05_timers/program/usage_log.txt
Labels: Ready for review
